### PR TITLE
CIF-684 - Upgrade Actions to NodeJS V10 runtime

### PR DESCRIPTION
**Pull request by herzog31**
Follow up PR to https://github.com/adobe/commerce-cif-common/pull/20.

### CODE REVIEW

**Comment by cjelger** [comment]
I am not sure whether we really want to hard-code the node version, up to now using `nodejs:default` basically "upgraded" us automatically from node6 to node8 to node10 ... I see pros and cons for using `nodejs:default` (always latest version, but might break) vs. using `nodejs:10` (more control over version, but might become obsolete if we don't manually upgrade), maybe we should have a quick discussion with the team before we decide.

**Comment by mhaack** [comment]
Is `nodejs:default` pointing always to the latest aka. node10 now or is it pinned to a fixed version like node6 and not updated automatically?

**Comment by cjelger** [comment]
I think this depends on the OpenWhisk platform itself, like Bluemix or Runtime. They choose what images they allow, and what `default` points to.

**Comment by herzog31** [comment]
@cjelger IMO we should be very explicit about which Node versions we support and which we don't. That said, I think using `nodejs:10` is the safest way to ensure we use the correct container. Also for Runtime, they not only provide a single `nodejs:10` runtime, there is a fat version as well and there might be more versions in the future.

We should add our requirements here to the documentation.

**Pull request merged**
